# Copyright Red Hat
# Run `make samples` if you modified the orginal file located in the project resources directory
apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  name: compute-operator
spec:
  reference:
    workspace:
      path: root:{{ .Organization }}
      exportName: compute-apis
  acceptedPermissionClaims:
  - group: workload.kcp.dev
    identityHash: edb6dc430960a1943f33a077f5ab8c69877f6e96ea70fbc962fe618f14268b38
    resource: synctargets
